' Copyright (C) 2025 - present Murat Yahsi, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml SchiffService

skinparam classAttributeIconSize 0

package java.util {
    interface List<T>
    interface Map<K, V>
    class UUID
}

package org.springframework {
    package stereotype {
        interface Service
    }

    package transaction.annotation {
        interface Transactional
    }

    package security.core.userdetails {
        interface UserDetails
    }

    List .right[hidden].> UserDetails
}

package com.acme.schiff {
    package entity {
        class Schiff << entity >>

        Schiff .up[hidden].> UUID
        Schiff .up[hidden].> UserDetails
        Schiff .up[hidden].> Service
        Schiff .up[hidden].> Transactional
    }

    package repository {
        interface SchiffRepository << control >>
    }

    package service #DDDDDD {
        class SchiffService << control >> << @Service >> {
            + findById(id: UUID): Schiff
            + find(suchkriterien: Map<String, List<String>>): Collection<Schiff>
        }

        SchiffService o-right-> "1" SchiffRepository : repo
        SchiffService .up.> Schiff
        SchiffService .up.> UUID
        SchiffService .up.> List
        SchiffService .up.> Map
        SchiffService .up.> Service
        SchiffService ..> Transactional
        SchiffService ..> UserDetails
    }
}

hide empty members

footer (c) Murat Yahsi

@enduml
